start:
	docker-compose -f docker/docker-compose.yaml up -d

be_bash:
	docker exec -it jest-test-2048 bash

run_test:
	docker exec -it jest-test-2048 npm test

run_test_background:
	docker exec -it jest-test-2048 npm test
